# Generated by Django 4.2.3 on 2023-08-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_advertisement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(default='', upload_to='advert/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
